basePath: /api/v1
definitions:
  model.Product:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      price:
        type: integer
      quantity:
        type: integer
    type: object
  request.ProductRequest:
    properties:
      description:
        type: string
      name:
        type: string
      price:
        type: integer
      quantity:
        type: integer
    type: object
info:
  contact: {}
  description: This is an API documentation for Erajaya.
  title: Erajaya API Documentation
  version: "1.0"
paths:
  /products:
    get:
      consumes:
      - application/json
      description: Get a list of products
      parameters:
      - description: 'Sort parameters in the format ''column:direction[,column2:direction]''.
          Example: created_at:desc,price:asc'
        in: query
        name: sort
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: List products
      tags:
      - Product
    post:
      consumes:
      - application/json
      description: Add a new product
      parameters:
      - description: Product details
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/request.ProductRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.Product'
        "400":
          description: Bad Request
          schema:
            additionalProperties: true
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Add a new product
      tags:
      - Product
swagger: "2.0"
